I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 30, in script
    narrator default "Привет, я Рассказчик"
Exception: Say has image attributes ('default',), but there's no image tag associated with the speaking character.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 30, in script
    narrator default "Привет, я Рассказчик"
  File "C:\Users\artem\Downloads\renpy-8.2.0-sdk\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "C:\Users\artem\Downloads\renpy-8.2.0-sdk\renpy\ast.py", line 615, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\artem\Downloads\renpy-8.2.0-sdk\renpy\exports.py", line 1493, in say
    who(what, *args, **kwargs)
  File "C:\Users\artem\Downloads\renpy-8.2.0-sdk\renpy\character.py", line 1329, in __call__
    old_attr_state = self.handle_say_attributes(False, interact)
  File "C:\Users\artem\Downloads\renpy-8.2.0-sdk\renpy\character.py", line 1148, in handle_say_attributes
    if self.resolve_say_attributes(predicting, attrs):
  File "C:\Users\artem\Downloads\renpy-8.2.0-sdk\renpy\character.py", line 1074, in resolve_say_attributes
    raise Exception("Say has image attributes %r, but there's no image tag associated with the speaking character." % (attrs,))
Exception: Say has image attributes ('default',), but there's no image tag associated with the speaking character.

Windows-10-10.0.22621 AMD64
Ren'Py 8.2.0.24012702
Затерянный в Институте PRE ALPHA
Wed Jan 31 21:15:00 2024
